services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 8.1
    image: lnmp:8.1
    container_name: php81
    volumes:
      - ./:/app/public
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:3306:3306"
